# -*- coding: utf-8 -*-
"""diabetes_patient_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhxPXinU5IXgDA6Tv0Nz-yKCxPlXuoOf

Importing basic libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Importing dataset"""

dataset= pd.read_csv("diabetes.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

"""Splitting dataset"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=12)

print(y_test)

"""Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=np.array(sc.fit_transform(X_train))
print(X_train)

from sklearn.svm import SVC
model=SVC()
model.fit(X_train, y_train)
y_pred=model.predict(np.array(sc.fit_transform(X_test)))

from sklearn.metrics import accuracy_score, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))